variables:
  baseimg: "docker-registry.pdbld.f5net.com/${CI_PROJECT_NAMESPACE}/k8s-bigip-ctlr"

stages:
  - sanity
  - build
  - deploy

python unit test:
  image: "python:2.7"
  stage: build
  script:
    - make local-python-test
  tags:
    - docker

prod build:
  stage: build
  tags:
    - docker-build
  script:
    - export BUILD_IMG_TAG="${baseimg}-devel:${CI_BUILD_REF}"
    - export CLEAN_BUILD=true
    - make docs
    - ./build-tools/build-release-artifacts.sh
  coverage: "/coverage:\\s+(.*)\\%\\s+of\\s+statements$/"
  artifacts:
    paths:
      - _docker_workspace
      - flatfile_attributions.json
      - golang_attributions.json
      - pip_attributions.json
      - docs/_static/ATTRIBUTIONS.md
      - docs/_build/html

# The official alpine image doesn't support race.
# Use a different build env for debug
debug build:
  stage: build
  tags:
    - docker-build
  script:
    - export BUILD_IMG_TAG="${baseimg}-devel:${CI_BUILD_REF}"
    - ./build-tools/build-debug-artifacts.sh
  artifacts:
    paths:
      - _docker_workspace

sanity verification:
  image: "golang:1.7.5"
  stage: sanity
  tags:
    - docker
  script:
    - make verify

schema test:
  image: "f5yacobucci/node6.2-wily:latest"
  stage: sanity
  script:
    - npm install jsonschema nodeunit
    - bash schemas/scripts/run-tests.sh
  tags:
    - docker

# Create the docker container and upload it to the internal docker registry with the tags
#   <PROJ_NAMESPACE>/k8s-bigip-ctlr:<COMMIT_ID>
#   <PROJ_NAMESPACE>/k8s-bigip-ctlr:<BRANCH>
#   <PROJ_NAMESPACE>/k8s-bigip-ctlr:<BRANCH>-<BUILD_ID>
dockerize:
  stage: deploy
  tags:
    - docker-build
  script:
    - export IMG_TAG="${baseimg}:${CI_BUILD_REF}"
    - export BUILD_IMG_TAG="${baseimg}-devel:${CI_BUILD_REF}"
    - export CLEAN_BUILD=true
    - ./build-tools/build-release-images.sh
    - docker tag "$IMG_TAG" "$baseimg:$CI_BUILD_REF_NAME"
    - docker tag "$IMG_TAG" "$baseimg:$CI_BUILD_REF_NAME-$CI_BUILD_ID"
    - docker push "$IMG_TAG"
    - docker push "$baseimg:$CI_BUILD_REF_NAME"
    - docker push "$baseimg:$CI_BUILD_REF_NAME-$CI_BUILD_ID"
  dependencies:
    - prod build


Publish docs to internet:
   # Publish ONLY 1.0-stable to the internet.
   image: docker-registry.pdbld.f5net.com/tools/containthedocs:master
   stage: deploy
   tags:
    - docker
   only:
    - 1.0-stable@velcro/k8s-bigip-ctlr
   dependencies:
     - prod build
   script:
     - publish-product-docs-to-prod connectors/k8s-bigip-ctlr v1.0
