language: bash
sudo: required
services:
  - docker

before_install:
  - docker pull golang:1.7.5
  - docker pull node:6.11.0-slim
  - docker pull f5devcentral/containthedocs

script:
  - set -e
  - docker run --rm -it -v `pwd`:`pwd` -w `pwd` node:6.11.0-slim build-tools/schema-tests.sh
  - if [ "$DOCKER_NAMESPACE" == "" ]; then DOCKER_NAMESPACE="local"; fi
  - BASE_PUSH_TARGET="$DOCKER_NAMESPACE/k8s-bigip-ctlr"
  - |
    if [ "$DOCKER_P" == "" -o "$DOCKER_U" == "" -o $DOCKER_NAMESPACE == "" ]; then
      echo "[INFO] Docker user, password, or namespace vars absent from travis-ci."
      echo "[INFO] See README.md section 'build' to configure travis with DockerHub."
    else
      docker login -u="$DOCKER_U" -p="$DOCKER_P"
      DOCKER_READY="true"
    fi
  - export IMG_TAG="${BASE_PUSH_TARGET}:${TRAVIS_COMMIT}"
  - export BUILD_IMG_TAG="${BASE_PUSH_TARGET}-devel:${TRAVIS_COMMIT}"
  - export CLEAN_BUILD=true
  - ./build-tools/build-devel-image.sh
  - ./build-tools/run-in-docker.sh make verify
  - ./build-tools/build-debug-artifacts.sh
  - ./build-tools/build-release-artifacts.sh
  - ./build-tools/build-release-images.sh
  - docker tag "$IMG_TAG" "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH"
  - docker tag "$IMG_TAG" "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH-n-$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID"
  - |
    if [ "$DOCKER_READY" ]; then
      docker push "$IMG_TAG"
      docker push "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH"
      docker push "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH-n-$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID"
    fi
  - make docs

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: 1.1-stable
      repo: F5Networks/k8s-bigip-ctlr
    script:
      - ./build-tools/deploy-docs.sh publish-product-docs-to-prod connectors/k8s-bigip-ctlr v1.1

notifications:
  slack:
    rooms:
      secure: mStBSaHe009xjilMEq5YwRmiYAB+oWZkKe1nk6rYebxw1uxVSe18lXkq9dhmX9a7nvko1iLvVYeXhmwE4ZWfnYVeMkaWq5/P3Rx0f453oEeM5SvqgoJfDPFyKqwBQgeIcOkZ+RMXiJRynPhb8BvnVMi24ZYUUpNP45TWWoBXHXg3xaPaFXQucZpHpPFYKZt8V5/aRhLTDhzvNP1o//ijgTuKDp2zuRSmVin5ofCEi78fDVIX5UXxvK47xx0dM5Lg8JFx/Tz9NcLreWsnz2NrRHxFwaxvGQiZAIamUwGCJKAoS+WlRVtcLuyB+FFfwaO0EaTKJr/5OWv8uhpK7pZfvfL//ShIHIf4FeCiOZG6s+PNiwzmxjVsX8CkZDqIvW+arGYA9OcYwKzLKBi5fR0SQzr2Eu+w53BhvutHzl7uok8XcxIzlo6zNaR23kYR9chnnIFvAwhugHa2iSoilAohsrf0nBNdDj0G2ObZSi4j68mQhn3fTHZzEDE3TddwnHcMgHOSkPFIZZJJZ4MrY5Ky1MuaZocOqCSPJlpPpd5EoJdBjozR5Coqsek3W1iaEgKVKsDuCvqsEHpI5JTLrJb9Q7g47O0dmDDOteQWDY6BJB/oFKjg5E+uN4qWCP99ydCS8UMTEdedZ/MZu2uGHeNgchRSsiLpFSOwoR/QlC2ezGQ=
